
const players = [
  // Juventus
  "Daniele Rugani",
  "João Mário",
  "Andrea Cambiaso",
  "Juan Cabal",
  "Jonas Rouhi",
  "Manuel Locatelli",
  "Teun Koopmeiners",
  "Vasilije Adžić",
  "Filip Kostić",
  "Khéphren Thuram",
  "Fabio Miretti",
  "Weston McKennie",
  "Francisco Conceição",
  "Dušan Vlahović",
  "Kenan Yıldız",
  "Edon Zhegrova",
  "Arkadiusz Milik",

  // AC Milan
  "Pietro Terracciano",
  "Mike Maignan",
  "Lorenzo Torriani",
  "Pervis Estupiñán",
  "Koni De Winter",
  "Fikayo Tomori",
  "Zachary Athekame",
  "Davide Bartesaghi",
  "Youssouf Fofana",
  "Ardon Jashari",
  "Ruben Loftus-Cheek",
  "Luka Modrić",
  "Christian Pulisic",
  "Adrien Rabiot",
  "Samuele Ricci",
  "Alexis Saelemaekers",
  "Santiago Giménez",
  "Rafael Leão",
  "Christopher Nkunku",

  // AS Roma
  "Devis Vásquez",
  "Radosław Żelezny",
  "Mile Svilar",
  "Devyne Rensch",
  "Angeliño",
  "Evan Ndicka",
  "Zeki Çelik",
  "Mario Hermoso",
  "Gianluca Mancini",
  "Anass Salah-Eddine",
  "Wesley",
  "Buba Sangaré",
  "Daniele Ghilardi",
  "Bryan Cristante",
  "Lorenzo Pellegrini",
  "Neil El Aynaoui",
  "Manu Koné",
  "Alessandro Romano",
  "Niccolò Pisilli",
  "Artem Dovbyk",
  "Evan Ferguson",
  "Matías Soulé",
  "Paulo Dybala",
  "Leon Bailey",
  "Tommaso Baldanzi",
  "Stephan El Shaarawy",
  // SSC Napoli (Mercato estivo confermato) :contentReference[oaicite:8]{index=8}
  "Giuseppe Ambrosino",
  "Sam Beukema",
  "Walid Cheddira",
  "Kevin De Bruyne",
  "Eljif Elmas",
  "Miguel Gutiérrez",
  "Rasmus Højlund",
  "Noa Lang",
  "Lorenzo Lucca",
  "Luca Marianucci",
  "Vanja Milinković-Savić",
  "Coli Saco",
  "Antonio Vergara",
  "Alessandro Zanoli",
  "Jens Cajuste",
  "Antonio Cioffi",
  "Giuseppe D'Agostino",
  "Luigi D'Avino",
  "Jesper Lindstrøm",
  "Victor Osimhen",
  "Emanuele Rao",
  "Lorenzo Sgarbi",
  "Gianluca Vigliotti",
  "Alessio Zerbin",

  // Inter Milan (nuovi acquisti confermati) :contentReference[oaicite:9]{index=9}
  "Manuel Akanji",
  "Petar Sučić",
  "Luis Henrique",
  "Ange-Yoan Bonny",
  "Francesco Pio Esposito", 
  // Lazio (prima squadra confermata)
  "Christos Mandas",
  "Alessio Furlanetto",
  "Ivan Provedel",
  "Samuel Gigot",
  "Luca Pellegrini",
  "Patric",
  "Alessio Romagnoli",
  "Nuno Tavares",
  "Oliver Provstgaard",
  "Manuel Lazzari",
  "Mario Gila",
  "Adam Marušić",
  "Matías Vecino",
  "Nicolò Rovella",
  "Fisayo Dele-Bashiru",
  "Mattéo Guendouzi",
  "Reda Belahyane",
  "Toma Bašić",
  "Danilo Cataldi",
  "Pedro",
  "Mattia Zaccagni",
  "Taty Castellanos",
  "Tijjani Noslin",
  "Gustav Isaksen",
  "Boulaye Dia",
  "Matteo Cancellieri",
  "Saná Fernandes",

  // Atalanta (mercato estivo aggiornato)
  "Marco Sportiello",
  "Honest Ahanor",
  "Mitchel Bakker",
  "Ben Godfrey",
  "Odilon Kossounou",
  "Marco Brescianini",
  "Yunus Musah",
  "Lazar Samardžić",
  "Nicola Zalewski",
  "Nikola Krstović",
  "Kamaldeen Sulemana",
  "El Bilal Touré", 
   // Fiorentina
  "Luca Lezzerini",
  "Tommaso Martinelli",
  "David de Gea",
  "Dodô",
  "Marin Pongračić",
  "Luca Ranieri",
  "Pietro Comuzzo",
  "Pablo Marí",
  "Eman Košpo",
  "Mattia Viti",
  "Niccolò Fortini",
  "Tariq Lamptey",
  "Eddy Kouadio",
  "Fabiano Parisi",
  "Simon Sohm",
  "Rolando Mandragora",
  "Abdelhamid Sabiri",
  "Hans Nicolussi Caviglia",
  "Robin Gosens",
  "Jacopo Fazzini",
  "Amir Richardson",
  "Cher Ndour",
  "Nicolò Fagioli",
  "Gino Infantino",
  "Edin Džeko",
  "Albert Guðmundsson",
  "Moise Kean",
  "Riccardo Braschi",
  "Roberto Piccoli",
  "Christian Kouamé",

  // Lazio
  "Maximiano",
  "Christos Mandas",
  "Alessio Furlanetto",
  "Ivan Provedel",
  "Samuel Gigot",
  "Luca Pellegrini",
  "Patric",
  "Alessio Romagnoli",
  "Oliver Provstgaard",
  "Nuno Tavares",
  "Mario Gila",
  "Matías Vecino",
  "Nicolò Rovella",
  "Fisayo Dele-Bashiru",
  "Mattéo Guendouzi",
  "Reda Belahyane",
  "Toma Bašić",
  "Pedro",
  "Mattia Zaccagni",
  "Taty Castellanos",
  "Tijjani Noslin",
  "Gustav Isaksen",
  "Boulaye Dia",
  "Matteo Cancellieri",
  "Saná Fernandes",
  "Gaetano Castrovilli",
  "Cristo Muñoz",
  "Gabriele Paolocci",
  "Vincenzo Di Gianni",

  // Atalanta
  "Marco Sportiello",
  "Honest Ahanor",
  "Mitchel Bakker",
  "Ben Godfrey",
  "Odilon Kossounou",
  "Marco Brescianini",
  "Yunus Musah",
  "Lazar Samardžić",
  "Nicola Zalewski",
  "Nikola Krstović",
  "Kamaldeen Sulemana",
  "El Bilal Touré",
  // Bologna (fonte: ESPN, WorldFootball, Transfermarkt)
  "Łukasz Skorupski",
  "Federico Ravaglia",
  "Massimo Pessina",
  "Stefan Posch",
  "Martin Vitík",
  "Babis Lykogiannis",
  "Federico Bernardeschi",
  "Nicolò Cambiaghi",
  "Santiago Castro",
  "Thijs Dallinga",
  "Lewis Ferguson",
  "Giovanni Fabbian",
  "Tommaso Pobega",
  "Ibrahim Sulemana",
  "Nadir Zortea",
  "Remo Freuler",
  "Nikola Moro",

  // Torino (fonte: Transfermarkt, ESPN, Tribuna)
  "Alberto Paleari",
  "Saúl Coco",
  "Ardian Ismajli",
  "Perr Schuurs",
  "Guillermo Maripán",
  "Saba Sazonov",
  "Adam Masina",
  "Giovanni Simeone",
  "Zakaria Aboukhlal",
  "Cyril Ngonge",
  "Duván Zapata",
  "Franco Israel",
  "Brian Bayeye",
  "Niels Nkounkou",
  "Marcus Holmgren Pedersen",
  "Tino Anjorin",

  // Sassuolo (fonte: Transfermarkt, ESPN, Tribuna)
  "Giacomo Satalino",
  "Stefano Turati",
  "Jay Idzes",
  "Tarik Muharemović",
  "Sebastian Walukiewicz",
  "Cas Odenthal",
  "Fali Candé",
  "Filippo Romagna",
  "Josh Doig",
  "Luca Moro",
  "Nicholas Pierini",
  "Andrea Pinamonti",
  "Cristian Volpato",
  "Armand Laurienté",
  "Alieu Fadera", 
   // Hellas Verona (nuovi acquisti)
  "Adi Kurti",
  "Giovane",
  "Enzo Ebosse",
  "Unai Núñez",
  "Domagoj Bradarić",
  "Victor Nelsson",
  "Armel Bella-Kotchap",
  "Gift Orban",
  "Moatasem Al-Musrati",

  // Udinese (mercato estivo)
  "Arthur Atta",
  "Lennon Miller",
  "Adam Buksa",
  "Alessandro Zanoli",
  "Luca Kjerrumgaard",
  "Saba Goglichidze",
  "Jakub Piotrowski",
  "Nicolò Zaniolo",
  "Alessandro Nunziante",
  "Nicolò Bertola",
  "Leonardo Buta",

  // Cagliari (rosa confermata)
  "Elia Caprile",
  "Giuseppe Ciocci",
  "Yerry Mina",
  "Adam Obert",
  "Michael Folorunsho",
  "Semih Kılıçsoy",
  "Zito Luvumbo",
  "Leonardo Pavoletti", 
  // Verona
  "Adi Kurti",
  "Giovane",
  "Enzo Ebosse",
  "Unai Núñez",
  "Domagoj Bradarić",
  "Victor Nelsson",
  "Armel Bella-Kotchap",
  "Gift Orban",
  "Moatasem Al-Musrati",

  // Udinese
  "Arthur Atta",
  "Lennon Miller",
  "Adam Buksa",
  "Alessandro Zanoli",
  "Luca Kjerrumgaard",
  "Saba Goglichidze",
  "Jakub Piotrowski",
  "Nicolò Zaniolo",
  "Alessandro Nunziante",
  "Nicolò Bertola",
  "Leonardo Buta",

  // Cagliari
  "Elia Caprile",
  "Giuseppe Ciocci",
  "Yerry Mina",
  "Adam Obert",
  "Michael Folorunsho",
  "Semih Kılıçsoy",
  "Zito Luvumbo",
  "Leonardo Pavoletti",

  // Sampdoria (fonte Transfermarkt / Wikipedia)
  "Simone Ghidotti",
  "Nicola Ravaglia",
  "Gaëtan Coucke",
  "Alessandro Pio Riccio",
  "Simone Romagnoli",
  "Giorgio Altare",
  "Lorenzo Venuti",
  "Simone Giordano",
  "Fabio Depaoli",
  "Alex Ferrari",
  "Stipe Vulikić",
  "Nikolas Ioannou",
  "Dennis Hadžikadunić",
  "Andrei Coubis",
  "Jordan Ferri",
  "Matteo Ricci",
  "Luigi Cherubini",
  "Alessandro Bellemo",
  "Liam Henderson",
  "Oliver Abildgaard",
  "Francesco Conti",
  "Leonardo Benedetti",
  "Antonín Barák",
  "Francesco Ferrara",
  "Marvin Çuni",
  "Massimo Coda",
  "Estanis Pedrola",
  "Víctor Narro",
  "Valerio Cinti",

  // Genoa (fonte ESPN & Transfermarkt)
  "Nicola Leali",
  "Benjamin Siegrist",
  "Daniele Sommariva",
  "Aarón Martín",
  "Leo Østigard",
  "Brooke Norton-Cuffy",
  "Johan Vásquez",

  // Lecce (fonte Reuters & BeSoccer)
  "Wladimiro Falcone",
  "Kialonda Gaspar",
  "Frédéric Guilbert",
  "Corrie Ndaba", 
   // Como
  "Jean Butez",
  "Henrique Menke",
  "Mauro Vigorito",
  "Nikola Čavlina",
  "Marc-Oliver Kempf",
  "Álex Valle",
  "Edoardo Goldaniga",
  "Alberto Dossena",
  "Alberto Moreno",
  "Diego Carlos",
  "Ignace Van Der Brempt",
  "Jacobo Ramón",
  "Mërgim Vojvoda",
  "Stefan Posch",
  "Lucas Da Cunha",
  "Martin Baturina",
  "Maxence Caqueret",
  "Nico Paz",
  "Máximo Perrone",
  "Sergi Roberto",

  // Cremonese
  "Emil Audero",
  "Giuseppe Pezzella",
  "Tommaso Barbieri",
  "Federico Baschirotto",
  "Alessio Zerbin",

  // Parma
  "Zion Suzuki",
  "Edoardo Corvi",
  "Emanuele Valeri",
  "Enrico Del Prato",
  "Mathias Løvik",
  "Sascha Britschgi",
  "Mariano Troilo",
  "Abdoulaye Ndiaye",
  "Botond Balogh",
  "Lautaro Valenti",
  "Adrián Bernabé",
  "Mandela Keita",
  "Nahuel Estévez",
  "Oliver Sørensen",
  "Gaetano Oristanio",
  "Christian Nahuel Ordonez",
  "Benjamin Cremaschi",
  "Nahuel Estévez",
  "Hernani", 
  // Pisa (fonti: ESPN, Transfermarkt, WorldFootball, FootballDatabase)
  "Adrian Semper",
  "Nícolas Andrade",
  "Simone Scuffet",
  "Ante Vukovic",
  "Samuele Angori",
  "Antonio Caracciolo",
  "Tomás Esteves",
  "Marius Marin",
  "Francesco Coppola",
  "Mateus Lusuardi",
  "Samuel Angori",
  "Giovanni Bonfanti",
  "Daniel Denoon",
  "Mateus Lusuardi", // già incluso
  "Henrik Meister",
  "Mbala Nzola",
  "Juan Cuadrado",
  "Louis Buffon",
  "Stefano Moreo",
  "Ebenеzer Akinsanmiro",

];


export default players;
